"""SW Beauty Salon (ryuken25/beauty-salon) — diagrams generated by the engine.

The ERD is built **straight from the imported CI4 migration schema** (no hand
data) — the real test that the importer + layout engine work on an external app.
The DFD context / Level-0 are authored from the documented salon domain
(CLAUDE.md): customer booking with fixed 30-min slots, DP verification, manual
WhatsApp, admin/pemilik panel, reporting.
"""
from __future__ import annotations

import os

from . import generic
from ..importers import import_ci4_migrations

# location of the cloned app relative to the repo root (override via env)
APP_DIR = os.environ.get(
    "BEAUTY_SALON_DIR",
    os.path.join(os.path.dirname(__file__), "..", "..", "..", "_beauty"))
MIGRATIONS = os.path.join(APP_DIR, "app", "Database", "Migrations")

# nicer Indonesian verbs per FK column (parent -verb-> child)
VERBS = {
    "layanan_id": "dipesan pada",
    "user_id": "melakukan",
    "booking_id": "memiliki",
}

STORE_NAMES = {
    "D1": "D1  users", "D2": "D2  layanan", "D3": "D3  bookings",
    "D4": "D4  booking_slots", "D5": "D5  transaksi",
    "D6": "D6  settings", "D7": "D7  booking_logs",
}


def _schema():
    return import_ci4_migrations(MIGRATIONS)


def build_erd_chen(order_fn=None):
    s = _schema()
    return generic.build_erd_chen(
        "ERD Chen (Beauty Salon)",
        "Entity Relationship Diagram (Chen) — SW Beauty Salon",
        s.entities(), s.relationships(VERBS), order_fn=order_fn)


def build_erd_crowsfoot():
    s = _schema()
    return generic.build_erd_crowsfoot(
        "ERD Crow's Foot (Beauty Salon)",
        "Entity Relationship Diagram (Crow's Foot) — SW Beauty Salon",
        s.entities(), s.relationships(VERBS))


def build_context():
    flows = [
        ("Pelanggan", "SYS", "Registrasi & login"),
        ("Pelanggan", "SYS", "Data booking & pilihan slot"),
        ("Pelanggan", "SYS", "Bukti pembayaran DP"),
        ("SYS", "Pelanggan", "Info layanan & promo"),
        ("SYS", "Pelanggan", "Kode booking & status"),
        ("Admin", "SYS", "Verifikasi booking & DP"),
        ("Admin", "SYS", "Data walk-in & layanan"),
        ("Admin", "SYS", "Pengaturan jam operasional"),
        ("SYS", "Admin", "Daftar booking & notifikasi"),
        ("Pemilik", "SYS", "Permintaan laporan"),
        ("SYS", "Pemilik", "Laporan pendapatan & analitik"),
    ]
    return generic.build_context(
        "Diagram Konteks (Beauty Salon)",
        "Diagram Konteks (Diagram 0) — SW Beauty Salon",
        "0\nSistem Informasi Booking SW Beauty Salon",
        ["Pelanggan", "Admin", "Pemilik"], flows)


def build_dfd0():
    data = {
        "id": "bs-dfd-level0", "name": "DFD Level 0 (Beauty Salon)",
        "type": "dfd-level0",
        "title": "DFD Level 0 (Overview) — SW Beauty Salon",
        "store_names": STORE_NAMES,
        "procs": [
            ("P1", "P1.0\nAutentikasi &\nAkun Pelanggan"),
            ("P2", "P2.0\nKelola Layanan"),
            ("P3", "P3.0\nProses Booking\n& Slot"),
            ("P4", "P4.0\nVerifikasi DP\n& Pembayaran"),
            ("P5", "P5.0\nPelaporan"),
            ("P6", "P6.0\nPengaturan"),
        ],
        "ext": {
            "P1": [("Pelanggan", [("Data registrasi/login", "to"),
                                  ("Status & sesi login", "from")])],
            "P2": [("Admin", [("Data layanan & promo", "to")]),
                   ("Pelanggan", [("Info layanan & promo", "from")])],
            "P3": [("Pelanggan", [("Pilihan slot & data booking", "to"),
                                  ("Kode booking & status", "from")]),
                   ("Admin", [("Verifikasi/tolak & walk-in", "to")])],
            "P4": [("Pelanggan", [("Upload bukti DP", "to")]),
                   ("Admin", [("Verifikasi DP", "to")])],
            "P5": [("Pemilik", [("Permintaan laporan", "to"),
                                ("Laporan pendapatan & analitik", "from")])],
            "P6": [("Admin", [("Ubah jam operasional & template", "to")])],
        },
        "store": {
            "P1": [("D1", "", [("Data akun", "to"), ("Verifikasi kredensial", "from")])],
            "P2": [("D2", "", [("Data layanan", "to"), ("Info layanan", "from")])],
            "P3": [("D3", "", [("Simpan booking", "to"), ("Data booking", "from")]),
                   ("D4", "", [("Tahan slot", "to"), ("Cek ketersediaan slot", "from")]),
                   ("D2", "", [("Harga & durasi layanan", "from")]),
                   ("D7", "", [("Catat aktivitas booking", "to")])],
            "P4": [("D5", "", [("Catat transaksi", "to")]),
                   ("D3", "", [("Update status pembayaran", "to")])],
            "P5": [("D3", "", [("Baca data booking", "from")]),
                   ("D5", "", [("Baca data transaksi", "from")])],
            "P6": [("D6", "", [("Simpan pengaturan", "to"),
                               ("Baca pengaturan", "from")])],
        },
    }
    return generic.build_dfd(data)


def build_all():
    return {
        "bs_diagram_konteks": build_context(),
        "bs_dfd_level0": build_dfd0(),
        "bs_erd_chen": build_erd_chen(),
        "bs_erd_crowsfoot": build_erd_crowsfoot(),
    }
